### PR TITLE
Updated combat and related code

### PR DESCRIPTION
**Pull request by Oen44**
* Fixed applying conditions
* Fixed onGetPlayerMinMaxValues skill value for distance weapons  with ammunition
* Fixed critical damage
* Leech working better
* Simplified doTargetCombat

This code is taken from https://github.com/otland/forgottenserver

### CODE REVIEW

**Comment by SaiyansKing** [comment]
> * Fixed onGetPlayerMinMaxValues skill value for distance weapons  with ammunition

From what I'm remember I've already fixed it but in different way.

Overall great will test it tomorrow.
However since it is supposed to be simplified why using the std::fma? It wouldn't get any extra performance in this case because fma instruction(if available and the fun fact is that many vps don't have cpu that support this instruction) have the same latency as fpu multiplying so it will result in the same cycles usage.

**Comment by Oen44** [comment]
> However since it is supposed to be simplified why using the std::fma?
Honestly? No clue why they add this to TFS repo. As you said, it won't affect performance at all, probably someone read that "fma is faster" and went with it, dunno.

Since I'm working with servers that moved to this repo (well, I told them to), I'm fixing/adjusting whatever is needed, so far combat was the biggest issue. There is one more issue, ExtendedOpcode enabling packet needs to be moved around, gonna PR that later.

**Comment by SaiyansKing** [comment]
> > However since it is supposed to be simplified why using the std::fma?
> 
> Honestly? No clue why they add this to TFS repo. As you said, it won't affect performance at all, probably someone read that "fma is faster" and went with it, dunno.
> 
> Since I'm working with servers that moved to this repo (well, I told them to), I'm fixing/adjusting whatever is needed, so far combat was the biggest issue. There is one more issue, ExtendedOpcode enabling packet needs to be moved around, gonna PR that later.

I'm not using ExtendedOpcode since I working on TFC which will not support it(also it looks like soon this packet header will be taken by Cipsoft) so I have no idea that there are some problems with it.

About combat nobody never report any issue with it and I haven't encounter any serious problems aside leech and I don't like that much taking anything from the main repository because it later result in 9 commits that fixes 1000 undefined behaviors like with revscripts(someone I know once reported out of memory error that happen due to fucked up action revscript register and it was instantly closed because in their opinion it is impossible that they have such bugs and they are surprised nobody even consider reporting anything).

**Comment by Oen44** [comment]
> About combat nobody never report any issue with it and I haven't encounter any serious problems aside leech

Critical damage not working is the biggest issue. You can see critical strike effect but there is no damage increase, it's easy to see why by looking at the code.

**Comment by SaiyansKing** [comment]
After some testings and analysing code there are some problems:
-code style - newlines before `else` that shouldn't be there
-critical damage sometimes is reduced by half in pvp and sometimes not(??)
-leeched and critical booleans are unnecessary
-due to "architectural" difference between main repository there is a problem with dispel condition that can cause conditions effects to be removed twice
-critical effect is sended unnecessary for every creature in aoe spells(loops aren't free for cpu)

If you aren't interested in fixing it(since it isn't your code after all) I can fix it.

**Comment by Oen44** [comment]
> If you aren't interested in fixing it(since it isn't your code after all) I can fix it.

I would love to but I'm way too busy (starting own company). I'm so sorry for throwing more work at you.

**Comment by SaiyansKing** [comment]
It's okay.

**Pull request closed without merging**
